### ISSUE TITLE
unexpected '?' in 

### ISSUE THREAD

**Issue by kristopherlarson** [alek13/slack#26]
Parse error: syntax error, unexpected '?' in  /vendor/alek13/slack/src/Client.php on line 130

I'm getting this error.

**Comment by alek13** [comment]
Hi @kristopherlarson , which php version do you use & which version of package ?

**Comment by alek13** [comment]
In version `2.0` (for now `2.0-dev` -- `master` branch) there is no php 5 support.
If you need version for php 5, you can use 1.x series (latest stable: `1.10.1`), which supports php 5.5 & 5.6
